apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
          - name: POSTGRES_USER
            value: "postgres_user"
          - name: POSTGRES_PASSWORD
            value: "12345"
          - name: POSTGRES_DB
            value: "scheduler_db"
        ports:
          - containerPort: 5432
