apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: scheduling-service-app:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: scheduling-app-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: scheduling-app-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: scheduling-app-secret
                key: POSTGRES_DATABASE
          - name: POSTGRES_HOST
            value: "postgres"
          - name: POSTGRES_PORT
            value: "5432"
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: scheduling-app-secret
                key: RABBITMQ_USER
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: scheduling-app-secret
                key: RABBITMQ_PASSWORD
          - name: RABBITMQ_HOST
            value: "rabbitmq"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_QUEUE
            value: "twap_orders"
