apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering-app
  template:
    metadata:
      labels:
        app: ordering-app
    spec:
      containers:
      - name: ordering-app
        image: ordering-service-app:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8111
        env:
          - name: POSTGRES_USER
            value: "postgres_user"
          - name: POSTGRES_PASSWORD
            value: "12345"
          - name: POSTGRES_HOST
            value: "postgres"
          - name: POSTGRES_DATABASE
            value: "scheduler_db"
          - name: POSTGRES_PORT
            value: "5432"
          - name: RABBITMQ_HOST
            value: "rabbitmq"
          - name: RABBITMQ_USER
            value: "rabbitmq_user"
          - name: RABBITMQ_PASSWORD
            value: "rabbitmq_password"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_QUEUE
            value: "twap_orders"
          - name: BYBIT_API_KEY
            value: I6VsJKmPlLBRWFXGZu
          - name: BYBIT_API_SECRET
            value: zhnmbHfVBds85leFlh7hctAE1CLbvrM3pYgu
