apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering-app
  template:
    metadata:
      labels:
        app: ordering-app
    spec:
      containers:
      - name: ordering-app
        image: ordering-service-app:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8111
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: ordering-app-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ordering-app-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: ordering-app-secret
                key: POSTGRES_DATABASE
          - name: POSTGRES_HOST
            value: "postgres"
          - name: POSTGRES_PORT
            value: "5432"
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: ordering-app-secret
                key: RABBITMQ_USER
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ordering-app-secret
                key: RABBITMQ_PASSWORD
          - name: RABBITMQ_HOST
            value: "rabbitmq"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_QUEUE
            value: "twap_orders"
          - name: BYBIT_API_KEY
            valueFrom:
              secretKeyRef:
                name: ordering-app-secret
                key: BYBIT_API_KEY
          - name: BYBIT_API_SECRET
            valueFrom:
              secretKeyRef:
                name: ordering-app-secret
                key: BYBIT_API_SECRET
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                name: ordering-app-secret
                key: MONGODB_USER
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ordering-app-secret
                key: MONGODB_PASSWORD
          - name: MONGODB_HOST
            value: "mongodb"
          - name: MONGODB_PORT
            value: "27017"
